auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 15m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  aws:
    s3: s3://${MINIO_BUCKET}
    region: ${MINIO_REGION}
    s3forcepathstyle: true
    endpoint: ${MINIO_ENDPOINT}

limits_config:
  retention_period: ${LOKI_RETENTION}

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: ${LOKI_RETENTION}
